using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
[System.Serializable]
public class SkillData 
{
    public float[,] color;
    public bool[] enabled;
    public float[] statValues;
    public int armorModify;
    public int damageModify;
    public int stealthModify;
    public int summonModify;
    public int oneHandModifyStat;
    public int twoHandModifyStat;
    public int lightArmorModifyStat;
    public int hardArmorModifyStat;
    public int alchemyModifyStat;
    public int battleSpellsModifyStat;
    public int recoverSpellsModifyStat;
    public int summonSpellModifyStat;
    public int archeryModifyStat;
    public SkillData()
    {
        color = new float[36, 3];
        enabled = new bool[36];
        statValues = new float[9];
        oneHandModifyStat = GameObject.Find("SkillManager").GetComponent<SkillManager>().oneHandModifyStat;
        twoHandModifyStat = GameObject.Find("SkillManager").GetComponent<SkillManager>().twoHandModifyStat;
        lightArmorModifyStat = GameObject.Find("SkillManager").GetComponent<SkillManager>().lightArmorModifyStat;
        hardArmorModifyStat = GameObject.Find("SkillManager").GetComponent<SkillManager>().hardArmorModifyStat;
        alchemyModifyStat = GameObject.Find("SkillManager").GetComponent<SkillManager>().alchemyModifyStat;
        battleSpellsModifyStat = GameObject.Find("SkillManager").GetComponent<SkillManager>().battleSpellsModifyStat;
        recoverSpellsModifyStat = GameObject.Find("SkillManager").GetComponent<SkillManager>().recoverSpellsModifyStat;
        summonModify = GameObject.Find("SkillManager").GetComponent<SkillManager>().summonSpellModifyStat;
        archeryModifyStat = GameObject.Find("SkillManager").GetComponent<SkillManager>().archeryModifyStat;
        armorModify = GameObject.Find("SkillManager").GetComponent<SkillManager>().armorModify;
        damageModify = GameObject.Find("SkillManager").GetComponent<SkillManager>().damageModify;
        stealthModify = GameObject.Find("SkillManager").GetComponent<SkillManager>().stealthModify;
        summonModify = GameObject.Find("SkillManager").GetComponent<SkillManager>().summonModify;
        statValues[0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().statsWindow.Find("OneHandSlider").GetComponent<Slider>().value;
        statValues[1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().statsWindow.Find("TwoHandSlider").GetComponent<Slider>().value;
        statValues[2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().statsWindow.Find("ArcherySlider").GetComponent<Slider>().value;
        statValues[3] = GameObject.Find("SkillManager").GetComponent<SkillManager>().statsWindow.Find("HardArmorSlider").GetComponent<Slider>().value;
        statValues[4] = GameObject.Find("SkillManager").GetComponent<SkillManager>().statsWindow.Find("LightArmorSlider").GetComponent<Slider>().value;
        statValues[5] = GameObject.Find("SkillManager").GetComponent<SkillManager>().statsWindow.Find("AlchemySlider").GetComponent<Slider>().value;
        statValues[6] = GameObject.Find("SkillManager").GetComponent<SkillManager>().statsWindow.Find("BattleSpellsSlider").GetComponent<Slider>().value;
        statValues[7] = GameObject.Find("SkillManager").GetComponent<SkillManager>().statsWindow.Find("RecoverSpellsSlider").GetComponent<Slider>().value;
        statValues[8] = GameObject.Find("SkillManager").GetComponent<SkillManager>().statsWindow.Find("SummonSpellsSlider").GetComponent<Slider>().value;
        color[0, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage1").GetComponent<Image>().color.r;
        color[0, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage1").GetComponent<Image>().color.g;
        color[0, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage1").GetComponent<Image>().color.b;
        enabled[0]=GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage1").GetComponent<Button>().interactable;
        color[1, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage2").GetComponent<Image>().color.r;
        color[1, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage2").GetComponent<Image>().color.g;
        color[1, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage2").GetComponent<Image>().color.b;
        enabled[1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage2").GetComponent<Button>().interactable;
        color[2, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage3").GetComponent<Image>().color.r;
        color[2, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage3").GetComponent<Image>().color.g;
        color[2, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage3").GetComponent<Image>().color.b;
        enabled[2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("SpellDamage3").GetComponent<Button>().interactable;
        color[3, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon1").GetComponent<Image>().color.r;
        color[3, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon1").GetComponent<Image>().color.g;
        color[3, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon1").GetComponent<Image>().color.b;
        enabled[3] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon1").GetComponent<Button>().interactable;
        color[4, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon2").GetComponent<Image>().color.r;
        color[4, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon2").GetComponent<Image>().color.g;
        color[4, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon2").GetComponent<Image>().color.b;
        enabled[4] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon2").GetComponent<Button>().interactable;
        color[5, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon3").GetComponent<Image>().color.r;
        color[5, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon3").GetComponent<Image>().color.g;
        color[5, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon3").GetComponent<Image>().color.b;
        enabled[5] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Summon3").GetComponent<Button>().interactable;
        color[6, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover1").GetComponent<Image>().color.r;
        color[6, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover1").GetComponent<Image>().color.g;
        color[6, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover1").GetComponent<Image>().color.b;
        enabled[6] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover1").GetComponent<Button>().interactable;
        color[7, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover2").GetComponent<Image>().color.r;
        color[7, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover2").GetComponent<Image>().color.g;
        color[7, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover2").GetComponent<Image>().color.b;
        enabled[7] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover2").GetComponent<Button>().interactable;
        color[8, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover3").GetComponent<Image>().color.r;
        color[8, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover3").GetComponent<Image>().color.g;
        color[8, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover3").GetComponent<Image>().color.b;
        enabled[8] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Recover3").GetComponent<Button>().interactable;
        color[9, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana1").GetComponent<Image>().color.r;
        color[9, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana1").GetComponent<Image>().color.g;
        color[9, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana1").GetComponent<Image>().color.b;
        enabled[9] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana1").GetComponent<Button>().interactable;
        color[10, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana2").GetComponent<Image>().color.r;
        color[10, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana2").GetComponent<Image>().color.g;
        color[10, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana2").GetComponent<Image>().color.b;
        enabled[10] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana2").GetComponent<Button>().interactable;
        color[11, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana3").GetComponent<Image>().color.r;
        color[11, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana3").GetComponent<Image>().color.g;
        color[11, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana3").GetComponent<Image>().color.b;
        enabled[11] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("MageSkills").transform.Find("Mana3").GetComponent<Button>().interactable;
        color[12, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health1").GetComponent<Image>().color.r;
        color[12, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health1").GetComponent<Image>().color.g;
        color[12, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health1").GetComponent<Image>().color.b;
        enabled[12] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health1").GetComponent<Button>().interactable;
        color[13, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health2").GetComponent<Image>().color.r;
        color[13, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health2").GetComponent<Image>().color.g;
        color[13, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health2").GetComponent<Image>().color.b;
        enabled[13] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health2").GetComponent<Button>().interactable;
        color[14, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health3").GetComponent<Image>().color.r;
        color[14, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health3").GetComponent<Image>().color.g;
        color[14, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health3").GetComponent<Image>().color.b;
        enabled[14] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Health3").GetComponent<Button>().interactable;
        color[15, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor1").GetComponent<Image>().color.r;
        color[15, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor1").GetComponent<Image>().color.g;
        color[15, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor1").GetComponent<Image>().color.b;
        enabled[15] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor1").GetComponent<Button>().interactable;
        color[16, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor2").GetComponent<Image>().color.r;
        color[16, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor2").GetComponent<Image>().color.g;
        color[16, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor2").GetComponent<Image>().color.b;
        enabled[16] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor2").GetComponent<Button>().interactable;
        color[17, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor3").GetComponent<Image>().color.r;
        color[17, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor3").GetComponent<Image>().color.g;
        color[17, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor3").GetComponent<Image>().color.b;
        enabled[17] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Armor3").GetComponent<Button>().interactable;
        color[18, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage1").GetComponent<Image>().color.r;
        color[18, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage1").GetComponent<Image>().color.g;
        color[18, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage1").GetComponent<Image>().color.b;
        enabled[18] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage1").GetComponent<Button>().interactable;
        color[19, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage2").GetComponent<Image>().color.r;
        color[19, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage2").GetComponent<Image>().color.g;
        color[19, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage2").GetComponent<Image>().color.b;
        enabled[19] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage2").GetComponent<Button>().interactable;
        color[20, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage3").GetComponent<Image>().color.r;
        color[20, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage3").GetComponent<Image>().color.g;
        color[20, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage3").GetComponent<Image>().color.b;
        enabled[20] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Damage3").GetComponent<Button>().interactable;
        color[21, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina1").GetComponent<Image>().color.r;
        color[21, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina1").GetComponent<Image>().color.g;
        color[21, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina1").GetComponent<Image>().color.b;
        enabled[21] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina1").GetComponent<Button>().interactable;
        color[22, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina2").GetComponent<Image>().color.r;
        color[22, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina2").GetComponent<Image>().color.g;
        color[22, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina2").GetComponent<Image>().color.b;
        enabled[22] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina2").GetComponent<Button>().interactable;
        color[23, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina3").GetComponent<Image>().color.r;
        color[23, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina3").GetComponent<Image>().color.g;
        color[23, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina3").GetComponent<Image>().color.b;
        enabled[23] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("PaladinSkills").transform.Find("Stamina3").GetComponent<Button>().interactable;
        color[24, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing1").GetComponent<Image>().color.r;
        color[24, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing1").GetComponent<Image>().color.g;
        color[24, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing1").GetComponent<Image>().color.b;
        enabled[24] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing1").GetComponent<Button>().interactable;
        color[25, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing2").GetComponent<Image>().color.r;
        color[25, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing2").GetComponent<Image>().color.g;
        color[25, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing2").GetComponent<Image>().color.b;
        enabled[25] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing2").GetComponent<Button>().interactable;
        color[26, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing3").GetComponent<Image>().color.r;
        color[26, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing3").GetComponent<Image>().color.g;
        color[26, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing3").GetComponent<Image>().color.b;
        enabled[26] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Pickpocketing3").GetComponent<Button>().interactable;
        color[27, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking1").GetComponent<Image>().color.r;
        color[27, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking1").GetComponent<Image>().color.g;
        color[27, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking1").GetComponent<Image>().color.b;
        enabled[27] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking1").GetComponent<Button>().interactable;
        color[28, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking2").GetComponent<Image>().color.r;
        color[28, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking2").GetComponent<Image>().color.g;
        color[28, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking2").GetComponent<Image>().color.b;
        enabled[28] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking2").GetComponent<Button>().interactable;
        color[29, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking3").GetComponent<Image>().color.r;
        color[29, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking3").GetComponent<Image>().color.g;
        color[29, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking3").GetComponent<Image>().color.b;
        enabled[29] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Breaking3").GetComponent<Button>().interactable;
        color[30, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth1").GetComponent<Image>().color.r;
        color[30, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth1").GetComponent<Image>().color.g;
        color[30, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth1").GetComponent<Image>().color.b;
        enabled[30] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth1").GetComponent<Button>().interactable;
        color[31, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth2").GetComponent<Image>().color.r;
        color[31, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth2").GetComponent<Image>().color.g;
        color[31, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth2").GetComponent<Image>().color.b;
        enabled[31] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth2").GetComponent<Button>().interactable;
        color[32, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth3").GetComponent<Image>().color.r;
        color[32, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth3").GetComponent<Image>().color.g;
        color[32, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth3").GetComponent<Image>().color.b;
        enabled[32] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("Stealth3").GetComponent<Button>().interactable;
        color[33, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack1").GetComponent<Image>().color.r;
        color[33, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack1").GetComponent<Image>().color.g;
        color[33, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack1").GetComponent<Image>().color.b;
        enabled[33] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack1").GetComponent<Button>().interactable;
        color[34, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack2").GetComponent<Image>().color.r;
        color[34, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack2").GetComponent<Image>().color.g;
        color[34, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack2").GetComponent<Image>().color.b;
        enabled[34] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack2").GetComponent<Button>().interactable;
        color[35, 0] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack3").GetComponent<Image>().color.r;
        color[35, 1] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack3").GetComponent<Image>().color.g;
        color[35, 2] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack3").GetComponent<Image>().color.b;
        enabled[35] = GameObject.Find("SkillManager").GetComponent<SkillManager>().skillInfo.transform.parent.transform.Find("RobberSkills").transform.Find("StealthAttack3").GetComponent<Button>().interactable;
    }
}
