// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_clear_the_crypt = "CgkIsOq307sFEAIQEA"; // <GPGSID>
        public const string achievement_assault = "CgkIsOq307sFEAIQCw"; // <GPGSID>
        public const string achievement_help_sister = "CgkIsOq307sFEAIQGw"; // <GPGSID>
        public const string achievement_masterrobber = "CgkIsOq307sFEAIQEg"; // <GPGSID>
        public const string achievement_craft = "CgkIsOq307sFEAIQGA"; // <GPGSID>
        public const string achievement_crypt = "CgkIsOq307sFEAIQDw"; // <GPGSID>
        public const string achievement_kill_solovey = "CgkIsOq307sFEAIQFQ"; // <GPGSID>
        public const string achievement_complete = "CgkIsOq307sFEAIQEQ"; // <GPGSID>
        public const string achievement_kill_bandits = "CgkIsOq307sFEAIQBg"; // <GPGSID>
        public const string achievement_robber = "CgkIsOq307sFEAIQAg"; // <GPGSID>
        public const string achievement_artelit__mushroom = "CgkIsOq307sFEAIQCQ"; // <GPGSID>
        public const string achievement_mage = "CgkIsOq307sFEAIQBA"; // <GPGSID>
        public const string achievement_first_adventure = "CgkIsOq307sFEAIQAQ"; // <GPGSID>
        public const string achievement_paladin = "CgkIsOq307sFEAIQAw"; // <GPGSID>
        public const string achievement_get_orders = "CgkIsOq307sFEAIQCg"; // <GPGSID>
        public const string achievement_find_traitor = "CgkIsOq307sFEAIQBQ"; // <GPGSID>
        public const string achievement_solovey_arrested = "CgkIsOq307sFEAIQFw"; // <GPGSID>
        public const string achievement_survey = "CgkIsOq307sFEAIQBw"; // <GPGSID>
        public const string achievement_storm = "CgkIsOq307sFEAIQDQ"; // <GPGSID>
        public const string achievement_stat = "CgkIsOq307sFEAIQGg"; // <GPGSID>
        public const string achievement_solovey_runned_away = "CgkIsOq307sFEAIQFg"; // <GPGSID>
        public const string achievement_the_great_paladin = "CgkIsOq307sFEAIQEw"; // <GPGSID>
        public const string achievement_archimage = "CgkIsOq307sFEAIQFA"; // <GPGSID>
        public const string achievement_shrine = "CgkIsOq307sFEAIQDg"; // <GPGSID>
        public const string achievement_traitor = "CgkIsOq307sFEAIQDA"; // <GPGSID>
        public const string achievement_skill = "CgkIsOq307sFEAIQGQ"; // <GPGSID>
        public const string achievement_supply = "CgkIsOq307sFEAIQCA"; // <GPGSID>

}

